# Container and Application Vulnerability Scanning Configuration
# Comprehensive security scanning setup for the learning platform

container_scanning:
  # Binary Authorization configuration
  binary_authorization:
    enabled: true
    policy_name: "learning-platform-policy"
    require_attestations: true
    
    # Attestation requirements
    attestations:
      vulnerability_scan:
        required: true
        max_severity: "MEDIUM" # Block HIGH and CRITICAL
      
      code_review:
        required: true
        min_reviewers: 2
      
      build_provenance:
        required: true
        verify_source: true

  # Container Analysis API
  container_analysis:
    enabled: true
    project_id: "rds-lms"
    
    # Scan configuration
    scan_on_push: true
    continuous_monitoring: true
    
    # Vulnerability database updates
    update_frequency: "daily"
    include_os_packages: true
    include_language_packages: true
    
    # Severity thresholds
    severity_thresholds:
      block_deployment:
        - "CRITICAL"
        - "HIGH"
      
      alert_only:
        - "MEDIUM"
        - "LOW"
    
    # Integration with CI/CD
    cicd_integration:
      fail_build_on_critical: true
      generate_reports: true
      export_to_security_center: true

  # Third-party scanning tools
  third_party_scanners:
    # Trivy scanner
    trivy:
      enabled: true
      scan_types:
        - "vuln" # Vulnerabilities
        - "secret" # Secrets detection
        - "config" # Configuration issues
      
      output_format: "json"
      ignore_unfixed: false
      
    # Snyk integration
    snyk:
      enabled: true
      project_id: "learning-platform"
      test_dependencies: true
      monitor_containers: true
    
    # Anchore Engine
    anchore:
      enabled: false # Optional additional scanner
      policy_bundle: "default"

# Application Security Scanning
application_scanning:
  # Static Application Security Testing (SAST)
  sast:
    enabled: true
    
    # SonarQube configuration
    sonarqube:
      enabled: true
      project_key: "learning-platform"
      
      # Quality gates
      quality_gates:
        coverage_threshold: 80
        duplicated_lines_density: 3
        maintainability_rating: "A"
        reliability_rating: "A"
        security_rating: "A"
    
    # CodeQL analysis
    codeql:
      enabled: true
      languages: ["javascript", "python", "java"]
      queries: ["security-extended", "security-and-quality"]
    
    # ESLint security rules
    eslint_security:
      enabled: true
      rules:
        - "security/detect-object-injection"
        - "security/detect-eval-with-expression"
        - "security/detect-non-literal-fs-filename"
        - "security/detect-unsafe-regex"

  # Dynamic Application Security Testing (DAST)
  dast:
    enabled: true
    
    # OWASP ZAP integration
    owasp_zap:
      enabled: true
      scan_types:
        - "baseline"
        - "full"
      
      target_urls:
        - "https://staging-learning.rdspos.com"
      
      authentication:
        enabled: true
        type: "form"
        username_field: "email"
        password_field: "password"
    
    # Custom security tests
    custom_tests:
      enabled: true
      test_suites:
        - "authentication_bypass"
        - "authorization_escalation"
        - "sql_injection"
        - "xss_prevention"

  # Interactive Application Security Testing (IAST)
  iast:
    enabled: false # Consider for future implementation
    runtime_monitoring: false

# Dependency Scanning
dependency_scanning:
  # npm audit for Node.js dependencies
  npm_audit:
    enabled: true
    audit_level: "moderate"
    fix_automatically: false # Manual review required
    
  # Python dependency scanning
  python_safety:
    enabled: true
    ignore_ids: [] # List of vulnerability IDs to ignore
    
  # License compliance
  license_scanning:
    enabled: true
    allowed_licenses:
      - "MIT"
      - "Apache-2.0"
      - "BSD-2-Clause"
      - "BSD-3-Clause"
    
    blocked_licenses:
      - "GPL-3.0"
      - "AGPL-3.0"
      - "LGPL-3.0"

# Secret Detection
secret_detection:
  # Git secret scanning
  git_secrets:
    enabled: true
    scan_history: true
    
    # Pre-commit hooks
    pre_commit_hooks:
      enabled: true
      block_commits: true
    
    # Patterns to detect
    patterns:
      - "api_key"
      - "private_key"
      - "password"
      - "token"
      - "secret"
      - "credential"
  
  # Cloud secret scanning
  cloud_secrets:
    enabled: true
    scan_gcp_secrets: true
    scan_environment_variables: true
    
    # Secret Manager integration
    secret_manager:
      audit_access: true
      rotation_alerts: true

# Security Alerts and Notifications
alerting:
  # Alert channels
  channels:
    email:
      enabled: true
      recipients: ["security@rdspos.com", "dev-team@rdspos.com"]
    
    slack:
      enabled: true
      webhook_url_env: "SLACK_SECURITY_WEBHOOK"
      channel: "#security-alerts"
    
    pagerduty:
      enabled: true
      integration_key_env: "PAGERDUTY_SECURITY_KEY"
  
  # Alert rules
  rules:
    critical_vulnerabilities:
      enabled: true
      severity: "CRITICAL"
      immediate_alert: true
    
    high_vulnerabilities:
      enabled: true
      severity: "HIGH"
      alert_delay: 300 # 5 minutes
    
    failed_security_scans:
      enabled: true
      consecutive_failures: 3
    
    secrets_detected:
      enabled: true
      immediate_alert: true

# Scanning Schedule
schedule:
  # Automated scans
  container_scans:
    daily: true
    on_code_change: true
    on_dependency_update: true
  
  dependency_scans:
    daily: true
    weekly_full_scan: true
  
  application_scans:
    dast_weekly: true
    sast_on_pr: true
  
  # Scan windows
  maintenance_windows:
    - start: "02:00"
      end: "04:00"
      timezone: "UTC"

# Reporting and Compliance
reporting:
  # Report generation
  generate_reports:
    security_dashboard: true
    vulnerability_trends: true
    compliance_reports: true
  
  # Report distribution
  distribution:
    security_team: "weekly"
    development_team: "daily"
    management: "monthly"
  
  # Compliance standards
  compliance:
    standards:
      - "OWASP Top 10"
      - "CIS Controls"
      - "NIST Cybersecurity Framework"
    
    audit_trails:
      enabled: true
      retention_days: 365

# Integration Configuration
integrations:
  # CI/CD pipeline integration
  cicd:
    github_actions: true
    cloud_build: true
    
    # Pipeline gates
    security_gates:
      block_on_critical: true
      block_on_secrets: true
      require_approval: true
  
  # Security tools integration
  security_center:
    enabled: true
    export_findings: true
    
  # Monitoring integration
  stackdriver:
    enabled: true
    custom_metrics: true