version: '3.8'

services:
  # Redis Cluster Nodes
  redis-node-1:
    image: redis:7.2.4-alpine
    container_name: redis-node-1
    command: >
      redis-server
      --port 7000
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-securepassword}
      --masterauth ${REDIS_PASSWORD:-securepassword}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - redis-node-1-data:/data
      - ./redis/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis-node-2:
    image: redis:7.2.4-alpine
    container_name: redis-node-2
    command: >
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-securepassword}
      --masterauth ${REDIS_PASSWORD:-securepassword}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - redis-node-2-data:/data
      - ./redis/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis-node-3:
    image: redis:7.2.4-alpine
    container_name: redis-node-3
    command: >
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-securepassword}
      --masterauth ${REDIS_PASSWORD:-securepassword}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - redis-node-3-data:/data
      - ./redis/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis-node-4:
    image: redis:7.2.4-alpine
    container_name: redis-node-4
    command: >
      redis-server
      --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-securepassword}
      --masterauth ${REDIS_PASSWORD:-securepassword}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - redis-node-4-data:/data
      - ./redis/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis-node-5:
    image: redis:7.2.4-alpine
    container_name: redis-node-5
    command: >
      redis-server
      --port 7004
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-securepassword}
      --masterauth ${REDIS_PASSWORD:-securepassword}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - redis-node-5-data:/data
      - ./redis/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis-node-6:
    image: redis:7.2.4-alpine
    container_name: redis-node-6
    command: >
      redis-server
      --port 7005
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-securepassword}
      --masterauth ${REDIS_PASSWORD:-securepassword}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - redis-node-6-data:/data
      - ./redis/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # Redis Sentinel Nodes
  redis-sentinel-1:
    image: redis:7.2.4-alpine
    container_name: redis-sentinel-1
    command: >
      redis-sentinel
      /usr/local/etc/redis/sentinel.conf
      --port 26379
      --requirepass ${SENTINEL_PASSWORD:-sentinelpassword}
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - redis-sentinel-1-data:/data
    networks:
      - redis-cluster
    restart: unless-stopped
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  redis-sentinel-2:
    image: redis:7.2.4-alpine
    container_name: redis-sentinel-2
    command: >
      redis-sentinel
      /usr/local/etc/redis/sentinel.conf
      --port 26380
      --requirepass ${SENTINEL_PASSWORD:-sentinelpassword}
    ports:
      - "26380:26380"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - redis-sentinel-2-data:/data
    networks:
      - redis-cluster
    restart: unless-stopped
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  redis-sentinel-3:
    image: redis:7.2.4-alpine
    container_name: redis-sentinel-3
    command: >
      redis-sentinel
      /usr/local/etc/redis/sentinel.conf
      --port 26381
      --requirepass ${SENTINEL_PASSWORD:-sentinelpassword}
    ports:
      - "26381:26381"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - redis-sentinel-3-data:/data
    networks:
      - redis-cluster
    restart: unless-stopped
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  # Cluster initialization service
  redis-cluster-init:
    image: redis:7.2.4-alpine
    container_name: redis-cluster-init
    command: >
      sh -c "
        echo 'Waiting for Redis nodes to be ready...' &&
        sleep 30 &&
        echo 'Creating Redis cluster...' &&
        redis-cli --cluster create
        redis-node-1:7000
        redis-node-2:7001
        redis-node-3:7002
        redis-node-4:7003
        redis-node-5:7004
        redis-node-6:7005
        --cluster-replicas 1
        -a ${REDIS_PASSWORD:-securepassword}
        --cluster-yes &&
        echo 'Redis cluster initialized successfully!'
      "
    networks:
      - redis-cluster
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    restart: "no"

  # Redis monitoring and health check
  redis-monitor:
    image: redis:7.2.4-alpine
    container_name: redis-monitor
    command: >
      sh -c "
        while true; do
          echo '=== Redis Cluster Health Check ===' &&
          redis-cli -h redis-node-1 -p 7000 -a ${REDIS_PASSWORD:-securepassword} cluster info &&
          redis-cli -h redis-node-1 -p 7000 -a ${REDIS_PASSWORD:-securepassword} cluster nodes &&
          echo '=== Sentinel Status ===' &&
          redis-cli -h redis-sentinel-1 -p 26379 -a ${SENTINEL_PASSWORD:-sentinelpassword} sentinel masters &&
          sleep 60
        done
      "
    networks:
      - redis-cluster
    depends_on:
      - redis-cluster-init
    restart: unless-stopped

volumes:
  redis-node-1-data:
    driver: local
  redis-node-2-data:
    driver: local
  redis-node-3-data:
    driver: local
  redis-node-4-data:
    driver: local
  redis-node-5-data:
    driver: local
  redis-node-6-data:
    driver: local
  redis-sentinel-1-data:
    driver: local
  redis-sentinel-2-data:
    driver: local
  redis-sentinel-3-data:
    driver: local

networks:
  redis-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16