steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/rds-lms/learning-platform/learning-platform:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/rds-lms/learning-platform/learning-platform:latest']
images:
  - 'us-central1-docker.pkg.dev/rds-lms/learning-platform/learning-platform:latest'
